# Generated by Django 3.0.4 on 2020-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200323_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='is_verified',
        ),
    ]
