# Generated by Django 3.0.4 on 2020-03-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_shopuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
